# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_lab3/design_lab3.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_lab3 || ORIG_REF_NAME==design_lab3} -quiet] -quiet

# IP: bd/design_lab3/ip/design_lab3_xup_nand2_0_0/design_lab3_xup_nand2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_lab3_xup_nand2_0_0 || ORIG_REF_NAME==design_lab3_xup_nand2_0_0} -quiet] -quiet

# IP: bd/design_lab3/ip/design_lab3_xup_nor2_0_0/design_lab3_xup_nor2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_lab3_xup_nor2_0_0 || ORIG_REF_NAME==design_lab3_xup_nor2_0_0} -quiet] -quiet

# IP: bd/design_lab3/ip/design_lab3_xup_xor2_0_0/design_lab3_xup_xor2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_lab3_xup_xor2_0_0 || ORIG_REF_NAME==design_lab3_xup_xor2_0_0} -quiet] -quiet

# XDC: bd/design_lab3/design_lab3_ooc.xdc
